CREATE database IF NOT EXISTS DATABASENAME;
CREATE USER 'USERNAME'@'localhost' IDENTIFIED BY 'PASSWORD';
GRANT ALL PRIVILEGES ON USERNAME.* TO 'DATABASENAME'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE Features (FeatureSID INT AUTO_INCREMENT NOT NULL, 
BatchNum INT NOT NULL,
Result TINYINT(1) NOT NULL,
ProbWin DOUBLE NOT NULL,
SeasonCode VARCHAR(4) NOT NULL,
LeagueCode VARCHAR(4) NOT NULL,
FixtureDate DATETIME NOT NULL,
HomeTeam VARCHAR(36) NOT NULL,
HomeFT INT NOT NULL,
AwayFT INT NOT NULL,
AwayTeam VARCHAR(36) NOT NULL,
BestOdds DOUBLE,
WorstOdds DOUBLE,
AvgOdds DOUBLE,
PRIMARY KEY(FeatureSID));
